// Constantes centralizadas para melhor manutenção
export const APP_CONFIG = {
  name: "DevFlow",
  version: "1.0.0",
  description: "Organize seus projetos e produtividade",
  author: "DevFlow Team",
  repository: "https://github.com/devflow/devflow",
} as const

export const STORAGE_KEYS = {
  projects: "devflow_projects",
  tasks: "devflow_tasks",
  snippets: "devflow_snippets",
  links: "devflow_links",
  pomodoroSessions: "devflow_pomodoro_sessions",
  profile: "devflow_profile",
  notifications: "devflow_notifications",
  pomodoroSettings: "devflow_pomodoro_settings",
  appSettings: "devflow_app_settings",
  demoMode: "devflow_demo_mode",
} as const

export const LIMITS = {
  maxImageSize: 5 * 1024 * 1024, // 5MB
  maxSkills: 20,
  maxProjects: 100,
  maxTasks: 500,
  maxSnippets: 200,
  maxLinks: 300,
  maxTitleLength: 100,
  maxDescriptionLength: 500,
  maxBioLength: 1000,
} as const

export const VALIDATION = {
  email: /^[^\s@]+@[^\s@]+\.[^\s@]+$/,
  url: /^https?:\/\/.+/,
  github: /^https?:\/\/(www\.)?github\.com\/.+/,
  linkedin: /^https?:\/\/(www\.)?linkedin\.com\/in\/.+/,
} as const

export const BRAZILIAN_STATES = [
  { value: "AC", label: "Acre" },
  { value: "AL", label: "Alagoas" },
  { value: "AP", label: "Amapá" },
  { value: "AM", label: "Amazonas" },
  { value: "BA", label: "Bahia" },
  { value: "CE", label: "Ceará" },
  { value: "DF", label: "Distrito Federal" },
  { value: "ES", label: "Espírito Santo" },
  { value: "GO", label: "Goiás" },
  { value: "MA", label: "Maranhão" },
  { value: "MT", label: "Mato Grosso" },
  { value: "MS", label: "Mato Grosso do Sul" },
  { value: "MG", label: "Minas Gerais" },
  { value: "PA", label: "Pará" },
  { value: "PB", label: "Paraíba" },
  { value: "PR", label: "Paraná" },
  { value: "PE", label: "Pernambuco" },
  { value: "PI", label: "Piauí" },
  { value: "RJ", label: "Rio de Janeiro" },
  { value: "RN", label: "Rio Grande do Norte" },
  { value: "RS", label: "Rio Grande do Sul" },
  { value: "RO", label: "Rondônia" },
  { value: "RR", label: "Roraima" },
  { value: "SC", label: "Santa Catarina" },
  { value: "SP", label: "São Paulo" },
  { value: "SE", label: "Sergipe" },
  { value: "TO", label: "Tocantins" },
] as const

export const PROGRAMMING_LANGUAGES = [
  "javascript",
  "typescript",
  "python",
  "java",
  "csharp",
  "cpp",
  "c",
  "php",
  "ruby",
  "go",
  "rust",
  "swift",
  "kotlin",
  "dart",
  "html",
  "css",
  "scss",
  "sql",
  "bash",
  "json",
  "yaml",
  "xml",
] as const

export const SKILL_SUGGESTIONS = [
  "JavaScript",
  "TypeScript",
  "React",
  "Next.js",
  "Vue.js",
  "Angular",
  "Node.js",
  "Python",
  "Java",
  "C#",
  "PHP",
  "Ruby",
  "Go",
  "Rust",
  "Swift",
  "Kotlin",
  "Flutter",
  "React Native",
  "HTML",
  "CSS",
  "Sass",
  "Tailwind CSS",
  "Bootstrap",
  "Material UI",
  "Styled Components",
  "MongoDB",
  "PostgreSQL",
  "MySQL",
  "Redis",
  "Firebase",
  "Supabase",
  "AWS",
  "Docker",
  "Git",
] as const

export const LINK_CATEGORIES = [
  "Documentação",
  "Tutorial",
  "Ferramenta",
  "Biblioteca",
  "Framework",
  "Blog",
  "Curso",
  "Referência",
  "Inspiração",
  "Outros",
] as const

export const EXPERIENCE_LEVELS = [
  { value: "Iniciante", label: "Iniciante (0-1 ano)" },
  { value: "Júnior", label: "Júnior (1-3 anos)" },
  { value: "Pleno", label: "Pleno (3-5 anos)" },
  { value: "Sênior", label: "Sênior (5-8 anos)" },
  { value: "Especialista", label: "Especialista (8+ anos)" },
] as const
